// <auto-generated />
using BooksApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230506103347_insertingDataToTable")]
    partial class insertingDataToTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksApp.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Pages")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("RealeseYear")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BooksDb");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Mohsen Ali",
                            BookTitle = "Code With Mohsen Ali",
                            Pages = 230,
                            RealeseYear = 2019
                        },
                        new
                        {
                            Id = 2,
                            Author = "Gul Buledai",
                            BookTitle = "Code With Gul Buledai",
                            Pages = 160,
                            RealeseYear = 2017
                        },
                        new
                        {
                            Id = 3,
                            Author = "Sameer Ali",
                            BookTitle = "Code With Sameer Ali",
                            Pages = 190,
                            RealeseYear = 2017
                        },
                        new
                        {
                            Id = 4,
                            Author = "Meer Ali",
                            BookTitle = "Code With Meer Ali",
                            Pages = 197,
                            RealeseYear = 2018
                        },
                        new
                        {
                            Id = 5,
                            Author = "Javed Ali",
                            BookTitle = "Code With Javed Ali",
                            Pages = 230,
                            RealeseYear = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
